### PR TITLE
Update to vintage_net 0.7

### PR DESCRIPTION
**Pull request by fhunleth**
VintageNet 0.7 splits out and renames networking technology
implementations. This propagates the change.

### CODE REVIEW

**Comment by jjcarstens** [comment]
Awesome!

Question - are we expecting new nerves_system_br with busy box to be released in all the images before this? If so, we could probably change busybox to an optional dep (or just remove)

**Comment by fhunleth** [comment]
Yes, the busy box change just needs to be released. I’m testing with it now, but held it back from this PR until new systems are out.

**Comment by jjcarstens** [comment]
I have this running on an rpi0. Things seem to be going well.

I've found that sometimes the wizard won't start automatically even though [`VintageNetWizard.run_wizard()`](https://github.com/jjcarstens/nerves_pack/blob/the-split/lib/nerves_pack/application.ex#L86) is called when starting the application. Not sure whats going on there, but it might be preexisting? Clues from the logs ¬

```
16:49:34.831 [info]  VintageNet(wlan0): loading config failed: :enoent

16:49:34.831 [info]  VintageNet: no starting config for wlan0 (:no_config)
```

**Comment by jjcarstens** [comment]
O, but calling `VintageNetWizard.run_wizard` manually worked fine and I've been able to go through the wizard flow successfully. (once that PR is up, I can move this comment there)

**Comment by fhunleth** [comment]
I've updated this PR for the latest release. I'm not sure what the issue is that you're running into.

**Pull request merged**
